MetOffice/CSET

.github/workflows/pr_ci.yml

Installing Iris on python 3.11 was broken for a time. (https://github.com/SciTools/iris/issues/5016) Iris now has a temporary fix in place, and is working on a more permanent one.

Reenable testing on python 3.11

---

.github/workflows/conda-lock.yml

A very minor aesthetic tooling fix so I'm just going to merge without any review.

Remove extra punctuation from conda lock CI commit message

---

.github/workflows/pre-commit-update.yml
.gitignore
pyproject.toml
src/CSET/__init__.py
src/CSET/operators/RECIPES/extract_instant_air_temp.toml
src/CSET/operators/__init__.py
src/CSET/operators/constraints.py
src/CSET/operators/misc.py
src/CSET/operators/plot.py
tests/test_constraints.py
tests/test_data/noop_recipe.toml
tests/test_data/plot_instant_air_temp.toml
tests/test_misc.py
tests/test_plots.py

This PR adds the necessary operators to do a simple plotting workflow, where a variable is isolated and then visualised.
Specifically it adds a time constraint operator, and a spacial plot operator.
(And also a noop operator for testing)

Add basic plotting capabilities

---

docs/source/operators.rst
docs/source/usage/index.rst
docs/source/usage/operator-recipes.rst

Documentation update to add installation instructions for using conda. Also adds missing operators to operators page, and improves some wording on the recipes page.

Update installation instructions to use conda and add missing operators to documentation

---

.github/workflows/pr_ci.yml
docs/source/index.rst
requirements/environment.yml

This adds some reasons why one would use CSET. This is partly to help promote it, but also helps to clarify the aims of the project for the developers.

Add documentation on rational

---

.github/workflows/pre-commit-update.yml

Security improvement suggested on Yammer. We where already pinning the versions, this just makes it more robust against malicious packages.
Fixes #117

Lock pre-commit config to specific SHA

---

src/CSET/operators/RECIPES/extract_instant_air_temp.yaml
src/CSET/operators/_internal.py
src/CSET/operators/constraints.py
src/CSET/operators/filters.py
src/CSET/operators/plot.py
src/CSET/operators/read.py
src/CSET/operators/write.py
tests/test_data/noop_recipe.yaml
tests/test_data/plot_instant_air_temp.yaml
tests/test_recipe_parser.py

A whole mix of various improvements and fixes.
Fixes #127

Operator runner improvements

---

development.yaml
docs/source/working-practices/index.rst
requirements/environment.yml

tox-conda does not currently support Tox version 4 (https://github.com/tox-dev/tox-conda/issues/156), so this PR pins tox to less than version 4.
It also adds a minimal environment for development, as tox pulls in the requirements to actually run CSET.

Pin version of tox used in environment

---

docs/source/usage/index.rst
docs/source/usage/operator-recipes.rst
src/CSET/__init__.py
src/CSET/_common.py
tests/test_cli.py
tests/test_run_recipes.py

This command was previously `cset operators`.
Fixes #139

Rename run command to bake

---

docs/source/usage/index.rst
src/CSET/__init__.py
src/CSET/recipes/__init__.py
src/CSET/recipes/extract_instant_air_temp.yaml
tests/test_cli.py
tests/test_recipes.py

This PR moves the recipes out of the internals of the operators module, and removes any direct internal reference to them in favour of always using files, as discussed in #103.
As part of this a new command has been implemented to create the default recipe files on disk, though I haven't yet though up a name.
Fixes #103

Add command to create recipes on disk

---

src/CSET/__init__.py

The version is determined at runtime by importlib.metadata.version().
Fixes #155

Add version command

---

docs/source/contributing/getting-started.rst

The conda environment creation is now done from a lock file.
Fixes #167.

Fix install instructions in docs

---

.github/workflows/pr_ci.yml

This allows running them on automatically created PRs, such as conda lock updates.

Allow PR checks to be run manually

---

src/CSET/operators/plot.py
src/CSET/recipes/ensemble_3_hour_air_temp.yaml
tests/operators/test_plots.py
tests/test_data/ensemble_air_temp.yaml

Adds postage stamp contour plots.
Still needs:
Fixes #159

Postage stamp plots

---

src/CSET/operators/plot.py

This fix allows postage stamp plots to be created from MOGREPS-UK data.
It also generalises it so it can do postage stamp plots of other fields than realization, tough I don't know if there will be too much interest in that.

Postage stamp plot fix

---

docs/source/reference/index.rst
docs/source/reference/internal.rst
docs/source/reference/operators.rst
src/CSET/operators/misc.py

[Rendered Documentation](https://tmpweb.net/ICXx-oq9ewHf/)

Document collapse operator

---

tests/operators/test_filters.py
tests/operators/test_plots.py
tests/test_cli.py
tests/test_common.py
tests/test_graph.py
tests/test_recipes.py
tests/test_run_recipes.py

Uses the exception testing and tmp_path helpers to significantly clean up tests.
Fixes #165.

Refactor tests to use PyTest helpers

---

docs/source/getting-started/installation.rst

This is faster, less likely to have package conflicts, and avoids issues with read-only base environments.
[Rendered documentation](https://tmpweb.net/BS8eBVp1ioXl/getting-started/installation)
Fixes #197
Also fixes https://github.com/MetOffice/CSET-workflow/issues/111

Document installing CSET into its own environment

---

.github/workflows/conda-lock.yml

This prevents the workflow failing when the previous update branch hasn't been merged. It was finding the branch already existed on the remote and failing.

Use hash of updated lock files in branch name

---

docs/source/contributing/getting-started.rst

Fixes #187
Adds the following note to the contributing getting started page.

Add note on updating a cloned repository

---

.github/workflows/documentation.yml
.github/workflows/pr_ci.yml

The docs will already be built as part of the documentation deploy process, so this was redundant.

Skip build-docs on push to main

---

.github/workflows/conda-lock.yml

It was trying to hash a folder, which doesn't work, and causes the workflow run to fail.

Fix globbing for lock file hashing

---

src/CSET/operators/filters.py
tests/operators/test_filters.py

Fix filter operator for filtering cube

---

.pre-commit-config.yaml

This allows adding test data much more easily.
Fixes #254

Fix pre-commit mangling test data

---

cset-workflow/meta/rose-meta.conf
src/CSET/operators/convection.py

fix the CAPE ratio description so that it is on two lines on the GUI, and minor formatting tweaks on CAPE ratio documentation.

CAPE ratio rose edit tweak

---

src/CSET/operators/read.py
tests/operators/test_read.py

Single cube read operator

---

.github/workflows/pre-commit-update.yml
.github/workflows/pull_request_checks.yml

This prevents subsequent runs crashing if older PRs have not been merged.

Hash updated config ensuring unique branch

---

cset-workflow/app/run_cset_recipe/bin/run-cset-recipe.py

os.getenvb requires the key to be bytes. A nice 1 character fix.
Fixes #383

Fix crash when running recipe from env var

---

src/CSET/graph.py
tests/test_graph.py

On non-desktop systems, such as HPCs, xdg-open doesn't exist. The created file can still be viewed manually, and the new error helps users discover the -o option to set the output.
Fixes https://github.com/MetOffice/CSET/issues/393
The new output if xdg-open fails is thus:
```
❯ cset graph -r recipe.yaml 
Graph rendered to /var/tmp/054629bb-a7b6-4eb8-87e1-e653015337fa.svg
Cannot automatically display graph. Specify an output with -o instead.
```
To do:

Graceful error when graphing without xdg-open

---

cset-workflow/bin/app_env_wrapper

This improves portability at sites that don't set this path by default. (Such as NCI in Australia.)
Also prepend to the path so that the CSET libraries are used preferentially.
Fixes https://github.com/MetOffice/CSET/issues/402

Handle LD_LIBRARY_PATH being unset

---

.github/workflows/conda-lock.yml
.github/workflows/pre-commit-update.yml

This means that the CI can run automatically after these changes, ensuring they don't break anything unknowingly.

Use GitHub App for making conda-lock update PRs

---

cset-workflow/flow.cylc
cset-workflow/includes/deterministic_domain_mean_surface_time_series.cylc
cset-workflow/includes/domain_mean_time_series_stash.cylc
cset-workflow/includes/plot_spatial_surface_model_field.cylc

This means the include files only need to contain the runtime sections for the recipes. In future we might even be able to avoid that.

Centralise scheduling into flow.cylc

---

cset-workflow/app/build_conda/bin/build_conda_env.sh
cset-workflow/bin/app_env_wrapper

All shell scripts that use `module load` modified to set `IFS` to a single space for the loop that loads the module, returning it after to its original value.

446 ifs in build conda

---

tests/operators/test_convection.py

Add licence header to convection tests

---

.github/workflows/documentation.yml

Using sphinx directly rather than tox is faster, and removes a layer of abstraction to keep things more understandable. This means that tox is now only used interactively.

Simplify documentation workflow

---

src/CSET/operators/plot.py

Includes the recipe title in the plot title, which should include things like the model, the value being plotted, etc.
Fixes #457

Include recipe title in plots title

---

src/CSET/operators/plot.py

Refactors the plotting code to use the explicit (object-oriented) matplotlib API. Figures are explicitly closed, preventing memory leaking. Also added a super-title to the postage stamp plots, so the diagnostic title is there too.
Fixes #481

Close figures after saving, and refactor plotting code

---

cset-workflow/includes/lfric_deterministic_domain_mean_surface_time_series.cylc
cset-workflow/includes/lfric_plot_spatial_surface_model_field.cylc
cset-workflow/meta/rose-meta.conf
src/CSET/_common.py
src/CSET/operators/filters.py
src/CSET/operators/misc.py
src/CSET/operators/read.py
src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
tests/operators/test_misc.py
tests/operators/test_read.py
tests/test_common.py

The UMified LFRic data contains cell methods about being a time point, where the UM has no methods in that case.
Fixes #309
Fixes #487

Add LFRic specific recipes

---

docs/source/contributing/releases.rst

Deprecation policy is based on pip's:
https://pip.pypa.io/en/stable/development/release-process/#deprecation-policy
Python support follows NEP 29:
https://numpy.org/neps/nep-0029-deprecation_policy.html
Incidentally this means we should drop python 3.9 in the April release. (https://github.com/MetOffice/CSET/issues/445)

Add explicit deprecation and python support policies

---

src/CSET/operators/misc.py
tests/operators/test_misc.py

Added generic arithmetic operators

---

docs/source/reference/recipe-format.rst

It wasn't documented anywhere.

Document category recipe key

---

src/CSET/operators/__init__.py

Quick fix to add regrid operator to `__init__.py`

Fix regrid operator missing from __init__.py

---

docs/source/changelog.rst

Fixes some names not being linked due to incorrect rst syntax.

Link missed names in changelog

---

docs/source/changelog.rst
src/CSET/operators/convection.py
src/CSET/operators/read.py
src/CSET/recipes/__init__.py
tests/operators/test_read.py
tests/test_recipes.py

Fixes #517
Emmit a warning when an input file does not exist. This makes it easier to understand what needs fixing in rose-suite.conf
Fixes #517

Warn when input files don't exist

---

docs/source/changelog.rst
docs/source/contributing/git.rst

The list is taken from the quest intro PowerPoint.
Fixes #560

Add list of useful git commands

---

cset-workflow/flow.cylc

Adding dummy tasks of `COLLATE` and `PARALLEL` families so cylc validates OK when there are no tasks using that families imported from the include files.
Not sure this is the perfect solution, it looks a bit clunky to have a task that does nothing.
Fixes #616 

add dummy tasks for collate and parallel

---

docs/source/changelog.rst
src/CSET/operators/regrid.py
tests/operators/test_regrid.py

Update regrid operator to use the generic utils function to identify x and y coordinates.
Fixes #

update regrid to use utils

---

cset-workflow/meta/rose-meta.conf

This updates the rose edit help text to clarify that any structured LFRic date is acceptable, rather than just data that has had its metadata converted to be like the UM.
Fixes #550

Note that structured LFRic is needed rather than UMified

---

src/CSET/operators/_utils.py
src/CSET/operators/plot.py
src/CSET/operators/regrid.py
tests/operators/test_utils.py

Quick fix to docstring specifying the expected return (wrong way round). No change in functionality/executable code.

Fix docstring typo in xycoord identifier in _utils

---

docs/source/changelog.rst
src/CSET/operators/read.py

Replaces "glob" with "filename_pattern", as that is what the argument to the read operator is called.

Clarify error message on missing files

---

.github/pull_request_template.md
docs/source/changelog.rst
docs/source/contributing/index.rst
docs/source/contributing/releases.rst

The changelog entries were a good idea, but they cause merge conflicts on almost every PR. Instead we would be better served with descriptive pull request titles, that in addition to being useful during development, allow automatically generating the GitHub release notes.
The changelog entries can then be copied in by the release manager.
Fixes #690

Suggest descriptive PR titles instead of changelog entry

---

src/CSET/operators/plot.py
src/CSET/recipes/inflow_layer_properties_plot.yaml
tests/operators/test_plots.py
tests/test_data/ensemble_air_temp.yaml

We've had this deprecated for a while now. Time to remove it.

Remove deprecated postage stamp contour plot operator

---

src/CSET/_common.py
src/CSET/operators/__init__.py
tests/test_common.py

We've had this deprecated for a while now. Time to remove it.

Remove unneeded fallback code for old recipe step keys

---

pyproject.toml

As CI starts from a fresh slate each time we won't yet have the resources downloaded. We do cache them, but caches are only per-branch, and thus we still need to download on the first run per branch.
Also removed the dateutil warning filter, as that issue has been fixed.

Ignore cartopy DownloadWarning in pytest

---

src/CSET/operators/constraints.py
tests/operators/test_constraints.py

This makes it the only variable constraint operator needed, and removes another point of difference between UM and LFRic recipes.
Fixes #589

Support STASH codes in generate_var_constraint

---

cset-workflow/includes/lfric_deterministic_domain_mean_surface_time_series.cylc
cset-workflow/includes/lfric_plot_spatial_surface_model_field.cylc
src/CSET/__init__.py
src/CSET/_common.py
src/CSET/operators/constraints.py
tests/test_common.py

This handles the double quoting that arises from CSET_ADDOPTS arguments never actually being parsed by a shell.

Unquote double quoted shell values

---

cset-workflow/meta/rose-meta.conf
cset-workflow/rose-suite.conf.example

It currently causes rose-edit to complain, and is not needed.

Remove invalid rose meta trigger for removed variable

---

.github/workflows/pull_request_checks.yml
.github/workflows/weekly-checks.yml

Don't check documentation hyperlinks in commit CI
This was too flakey to run this regularily, and blocks development if any linked external website goes down.
By having this in a separate workflow, we won't block development, but will still receive an email when the links don't resolve.
Fixes #748 

Don't check documentation hyperlinks in commit CI

---

tests/conftest.py

We now do a copy in the fixture itself, and remove unnecessary copies inside the tests, which makes the test code simpler.
Fixes #745

Make cube fixture safe to modify

---

src/CSET/operators/regrid.py
tests/operators/test_regrid.py

Fixes #720. Holding off implementation of caching regridder, as this only works if cubes in the cubelist passed to the function are on the same grid (which can't be assumed).

Regrid to take CubeList and Cubes

---

cset-workflow/app/fetch_fcst/opt/rose-app-mass.conf

Mass retrieval fix

---

cset-workflow/app/install_local_cset/bin/install-local-cset.py

This removes a presumption that the source directory is always called "CSET". `--no-deps` also stops pip searching for dependencies we already have in the conda environment.
Fixes #471

Copy source files from any named folder when installing locally

---

cset-workflow/app/install_local_cset/bin/install-local-cset.py

A small error that slipped through review, that now causes the install task to crash.

Add missing brackets to TemporaryDirectory call when installing local CSET

---

cset-workflow/app/housekeeping/bin/housekeep.sh
cset-workflow/app/install_website_skeleton/bin/install-website.sh
cset-workflow/app/run_cset_recipe/bin/run-cset-recipe.py
cset-workflow/flow.cylc
cset-workflow/meta/rose-meta.conf
cset-workflow/rose-suite.conf.example

Now the full output of CSET is under the workflow run directory, giving more consistent behaviour around cylc clean, moving output, and keeping old output when rerunning.
All web content is now saved under ${CYLC_WORKFLOW_SHARE_DIR}/web/ and a symbolic link is created from the webserver's directory.
Fixes #761

Move all website files under the workflow shared directory

---

cset-workflow/includes/transect.cylc
src/CSET/recipes/transect.yaml

Currently, when multiple variables are put into the GUI to perform the transect operator on, it overwrites each one with the latest one. This fix makes the tasks, output unique so it appears in the website and prevents conflicts.

Fix overwriting when using transect on multiple variables

---

src/CSET/operators/_plot_page_template.html

This ensures that the slider slides smoothly, as the image can be served from the browser cache.
I used JavaScript rather than `<link rel="preload" as="image" href="...">` as it was much easier to implement, as we don't currently have any way to loop over the plots at template time. If this changes we may want to switch, as HTML is both more explicit, and also taxes the browser less due to not having to create a non-displayed image element. The browser also seems to have more conservative limits for rel=preload, so it won't do as many concurrent requests.
Fixes #780

Preload plot images on web page

---

src/CSET/operators/constraints.py
tests/operators/test_constraints.py

This allows UM and LFRic recipes to be the same, so we can remove the LFRic specific ones.
~~This probably wants some tests before merging, but its 18:00 now, so that can wait for another day.~~ - Test now added.
Fixes #777
GitHub Copilot was used while making this change.

Allow Point cell methods for empty constraint, making it possible to unify UM and LFRic recipes

---

.github/workflows/pull_request_checks.yml

This saves CI time from being wasted on uninteresting commits.
Fixes #784

Cancel running PR checks if new commit is pushed

---

pyproject.toml

This setting was deprecated, so we now no longer specify it. The default behavor is now the same as what the setting gave us.

Stop ruff warning about ignore-init-module-imports

---

cset-workflow/includes/lfric_plot_spatial_mlevel_model_field.cylc
cset-workflow/includes/plot_spatial_mlevel_model_field.cylc

Parsing a float into the workflow to generate the task name causes errors, as a period is not an acceptable character in the cylc workflow. This change parses the dot into a p for the workflow task names. 
There might be a more general solution we could apply though, as I expect this might crop up with other diagnostics/variable combinations in new recipes.

Parsing of float in workflow

---

src/CSET/operators/plot.py
tests/operators/test_plots.py
tests/operators/test_transect.py

It is significantly faster than contourf, and gives a better idea of resolution.
GitHub Copilot was used in this PR.

Add pcolormesh plotting operator

---

src/CSET/recipes/generic_surface_spatial_plot_sequence.yaml

It is significantly faster, and gives a better idea of resolution.
Depends on #787, so should be merged afterwards.

Use pcolormesh for Quicklook surface spatial plots

---

src/CSET/_common.py
src/CSET/_workflow_utils/finish_website.py
src/CSET/_workflow_utils/run_cset_recipe.py
tests/test_common.py
tests/workflow_utils/test_finish_website.py
tests/workflow_utils/test_run_cset_recipe.py

This avoids a race condition if the file locking isn't working, such as on network filesystems, that causes plots to be missed from the index.
Fixes #614
Depends on #792
GitHub Copilot was used this PR.

Create the plot index in finish_website to avoid a data race between concurrent index writers

---

.github/workflows/pull_request_checks.yml

Fixes #827
GitHub broke this when the changed it to no-longer upload hidden files by default, without bumping the major version. (https://github.com/actions/upload-artifact/issues/602) Reeee!

Upload hidden coverage files to fix GitHub Actions breakage

---

cset-workflow/extra-meta/colorbar_dict_alphabetical.json

Adds entries for:
* air_temperature
* pressure
* relative_humidity
* wind_speed_of_gust

Add colorbar entries for more standard names

---

src/CSET/operators/__init__.py

Correct execute_recipe docstring; it takes an input directory

---

src/CSET/operators/plot.py

Fix colorbar min and max not being set on pcolormesh plots

---

src/CSET/_workflow_utils/fetch_data.py
tests/workflow_utils/test_fetch_data.py

Error fetch_fcst task when no data found for a model, as it usually indicates a typo in the data path

---

src/CSET/operators/_colorbar_definition.json

This ensures that the correct colorbar is used for plotting the rainfall.
Fixes #877

Fix spelling of stratiform_rainfall_rate in colorbar definition

---

src/CSET/operators/_colorbar_definition.json

Update the colorbar definitions to allow a reasonable, sample colorbar for standard variables available from model runs.
Fixes #806

Update colorbar definitions

---

pyproject.toml

It can't be measured outside of an editable install, and doesn't contain any logic.

Exclude __main__.py from test coverage measurement

---

src/CSET/operators/read.py
src/CSET/operators/regrid.py
tests/operators/test_regrid.py

This Pull Request is to merge in the changes in the branch associated with Issue #879. The aim is to deal with issues with incompatibility with longitude co-ordinates and ensure that, as far as possible, longitude co-ordinates and selected longitudes are in the range -180 degrees to 180 degrees.

Changes to fix longitude convention to be in the range -180 degrees to 180 degrees where possible

---

src/CSET/_workflow_utils/fetch_data.py

This restores compatibility with the iBoss TLS interception certificate that the Met Office is using. There is an upstream ticket open to get this certificate well formed, after which we can remove this line.
Fixes #903

Disable strict checking that TLS certificates are well formed

---

src/CSET/_workflow_utils/finish_website.py

Adding in the date to the CSET plots menu 

Add date to cset plot menu items

---

src/CSET/operators/plot.py

By default matplotlib tries to use an interactive backend for plotting. This is not only less efficient, but it also causes issues when running on non-GUI systems. We don't need it, so we can explicitly use a non- interactive backend.

Use non-interactive backend for plotting

---

pyproject.toml
requirements/environment.yml

This reverts commit d5c1bf0ee77a6d111a6822983cef79005504fb83.
For whatever reason the eccodes package fails to download on Met Office systems. This will require futher investigation, but backing out for now so it doesn't block building the conda environment from the main branch.

Revert "Add iris-grib to dev dependencies"

---

src/CSET/__init__.py

This prevents the sudden wall of tracebacks when you have just typoed a file path. The full traceback is still output for DEBUG logging (-vv).

Add nicer error messages for unhandled exceptions

---

.github/workflows/pull_request_checks.yml

The CI tests are now installed with a regular pip install, rather than being installed editabally. This ensures they are more realistic, as it slightly changes how data files are included into the package.

Use regular install for CI tests

---

src/CSET/operators/constraints.py

Update to documentation to cover hidden functionality in generate_levels_constraint which allows it to take any iterable coordinate and generate the required constraint. The focus here has been on ensemble realization to be able to stratify by ensemble member.
Fixes #132

Updates generate_levels_constraint documentation for ensemble functionality

---

src/CSET/operators/read.py

Log cubes that don't merge in `load_cube` operator

---

src/CSET/operators/read.py

When XIOS outputs LFRic to seperate streams, it requires there to be a global name attribute on the cube, containing the filename. As this attribute will be different between the different files, preventing merging, we need to remove it during data loading.

Remove unneeded `name` global attribute

---

cset-workflow/flow.cylc
cset-workflow/meta/rose-meta.conf

This makes debugging the workflow easier, without causing other runs to block on a single failed task.
Fixes #327

Require tasks to succeed in DEBUG mode

---

scripts/sort_json.py

Previously it would crash when trying to make a temporary file with a `/` in its name.

Handle sorting files outside the current directory in `sort_json.py` script

---

src/CSET/_common.py
src/CSET/graph.py
src/CSET/operators/__init__.py
src/CSET/operators/collapse.py
src/CSET/operators/filters.py
src/CSET/operators/misc.py
src/CSET/operators/write.py

This syntax has been available since python 3.9, which is beyond our minimum supported version of python 3.10, therefore it can all be removed.

Replace all remaining usage of typing.Union with `|`

---

src/CSET/__init__.py
src/CSET/operators/read.py

This limits warnings about unknown STASH codes to one per stash code, and filters out the list of fonts that matplotlib loves to log.

Reduce useless log messages

---

src/CSET/operators/ageofair.py

This avoids potential issues caused by mixing forking and threading in the same process. The default for multiprocessing will be changed to "spawn" in python 3.14.

Use "spawn" start method for multiprocessing

---

tests/operators/test_ageofair.py

We already have the test data leaded, so we should use it rather than recalculate it.

Remove unnecessary computation from age-of-air test

---

src/CSET/operators/ageofair.py

This avoids reinitialising the multiprocessing worker processes for each ensemble member, which is very expensive when using the "spawn" start method. This provides a considerable sppedup for large ensembles.

Share multiprocessing pool across ensemble members

---

cset-workflow/app/fetch_fcst/bin/fetch-data-mass.py
cset-workflow/app/fetch_fcst/rose-app.conf

We can make this public as MASS is accessible via JASMIN, and publicly documented there.
Fixes #1083

Add data fetching script from MASS

---

src/CSET/operators/_colorbar_definition.json

This adds a number of new variables taken from UKEP Plot's def_atm_vars.py. This also includes a large number of difference ranges.
The existing range values have been preserved where they were difference with the exception of cloud base height, which has been increased to a more reasonable sounding 1000m.
Particular attention should be paid to scientific reasonability when reviewing this PR.

Add additional colour bar definitions from UKEP Plot

---

cset-workflow/flow.cylc

I have had a few OOM errors with producing standard difference plots, and this is 648x648 domains. I suspect this will get worse with larger domains. I have mixed feelings about not addressing underlying issues, but might not be possible (matplotlib and cartopy are probably likely culprits), vs having something which doesn't intermittently fail on tasks. 4G is a modest amount (previous 2Gb).

Increase default memory to 4G for processes

---

tests/workflow_utils/test_fetch_data.py

This fixes the flaky tests that have come from caplog picking up a different test's logs now we are running under pytest-xdist.

Search for correct log_record in fetch_data tests

---

src/CSET/operators/_utils.py
src/CSET/operators/convection.py
src/CSET/operators/read.py
tests/operators/test_ageofair.py
tests/operators/test_collapse.py
tests/operators/test_convection.py
tests/operators/test_ensembles.py
tests/operators/test_filters.py
tests/operators/test_regrid.py
tests/operators/test_transect.py
tests/operators/test_utils.py

A fairly wide ranging set of test improvements. The main focus is ensuring we are using the CSET read operators to load data, so it is representative of what CSET will actually be handling. The only place that remains using `iris.load` is the tests for the read operators themselves.
There are also several robustness improvements to tests, to check the desired property directly rather than some tangential thing, such as the `repr()`.

Use CSET read operator to load test data, and improve various fragile tests

---

cset-workflow/flow.cylc

This ensures that housekeeping is only done after all the data is finished being used.
Fixes #1036
It will also be required for aggregating across case studies.

Remove housekeep_raw task from workflow

---

src/CSET/operators/collapse.py
tests/operators/test_collapse.py

Allow `collapse.collapse` to handle a CubeList

---

cset-workflow/includes/deterministic_domain_mean_surface_time_series_case_study_aggregation_validity_time.cylc
cset-workflow/includes/deterministic_domain_mean_vertical_model_level_profile_series_case_study_aggregation_validity_time.cylc
cset-workflow/includes/deterministic_domain_mean_vertical_pressure_profile_series_case_study_aggregation_validity_time.cylc
cset-workflow/includes/plot_spatial_mlevel_model_field_case_study_aggregation_validity_time.cylc
cset-workflow/includes/plot_spatial_plevel_model_field_case_study_aggregation_validity_time.cylc
cset-workflow/includes/plot_spatial_surface_model_field_case_study_aggregation_validity_time.cylc
cset-workflow/includes/spatial_surface_difference_case_study_aggregation_validity_time.cylc
cset-workflow/meta/diagnostics/rose-meta.conf
src/CSET/recipes/generic_mlevel_domain_mean_vertical_profile_series_case_aggregation_validity_time.yaml
src/CSET/recipes/generic_mlevel_spatial_plot_sequence_case_aggregation_mean_validity_time.yaml
src/CSET/recipes/generic_plevel_domain_mean_vertical_profile_series_case_aggregation_validity_time.yaml
src/CSET/recipes/generic_plevel_spatial_plot_sequence_case_aggregation_mean_validity_time.yaml
src/CSET/recipes/generic_surface_domain_mean_time_series_case_aggregation_validity_time.yaml
src/CSET/recipes/generic_surface_spatial_plot_sequence_case_aggregation_mean_validity_time.yaml
src/CSET/recipes/surface_spatial_difference_case_aggregation_mean_validity_time.yaml

Adds recipes and includes files, and updates diagnostics/rose-meta.conf for validity time aggregation.
Fixes #1033

Updates workflow for aggregation by validity time

---

src/CSET/operators/plot.py

Handle CubeLists in `plot_vertical_line_series` and `plot_scatter_plot`

---

cset-workflow/flow.cylc

This prevents the "family trigger on non-family namespace" error from occurring when you have no tasks enabled for a specific family of cylc tasks.
Fixes #616 (which reoccurred)

Add dummy tasks to prevent workflow graph failures

---

src/CSET/operators/read.py

`cube.coord("pressure").units` returns a `Unit` object, not str, which I am checking against. 

Fix issue where pressure coordinate returns Unit object, not str

---

src/CSET/operators/_colorbar_definition.json

fixes https://github.com/MetOffice/CSET/issues/1136

put in colorbar for surface_net_shortwave_flux_difference

---

src/CSET/operators/plot.py
tests/operators/test_plots.py

The user colorbar definition is now a per-variable override that will fall back to the default.
The possible variable names are now tried in order: Standard name, then long name, then var name. If none match then autoscaling viridis is used.

Search for all varnames and allow user colorbar override

---

src/CSET/operators/_colorbar_definition.json
src/CSET/operators/plot.py
tests/operators/test_plots.py

Support flexible pressure_level dependent colourbars

---

src/CSET/operators/_colorbar_definition.json

more surface plot colorbar changes off ticket #1136 

Fill out colorbar definitions for missing variables

---

.gitignore
cset-workflow/.gitignore

Now everything is in one repository, we don't need the seperate .gitignore for the workflow.

Unify .gitignore to cover both workflow and library

---

.github/workflows/documentation.yml
.github/workflows/pull_request_checks.yml
.github/workflows/weekly-checks.yml
cset-workflow/app/build_conda/bin/build_conda_env.sh
docs/source/contributing/getting-started.rst

Use the most recent python version throughout CSET. We are still supported back to 3.10, but aside from the tests for each python version everything should now be using 3.13.

Update environments used throughout CSET to python 3.13

---

.github/workflows/release.yml

The `released` trigger doesn't cover pre-releases, while the published trigger does.
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release

Allow release workflow to run on pre-releases

---

cset-workflow/app/build_conda/bin/build_conda_env.sh

Python 3.13 still has issues with the Met Office web proxy. It is going to be May when the certificate is replaced to fix this, so until then we will need to stick with python 3.12 for the workflow, as it needs to fetch the coastline information for cartopy.
Fixes #1167

Revert to python 3.12 for workflow environment

---

src/CSET/operators/_colorbar_definition.json

Ensure `_colorbar_definition.json` matches the expected first look spreadsheet by removing any repeated or UM colorbars. It does not add or change any of the colorbars.
Fixes #1176

Remove any repeated or UM colorbars

---

src/CSET/operators/_colorbar_definition.json

Amends a selection of pressure level color bars to vary with pressure to provide appropriate color bars.
Fixes #1179 

Add colorbar ranges for different pressure levels

---

src/CSET/_workflow_utils/finish_website.py
src/CSET/operators/plot.py
tests/operators/test_plots.py

This ensures the correct cycle point datetime is picked up. The date is not set for case study aggregation plots as there isn't a sensible date to pick.
Fixes #940

Set website display date at plot creation

---

src/CSET/operators/plot.py

Fix timeseries ylim based on JSON entries, and add gridlines.

---

src/CSET/__init__.py
src/CSET/_workflow_utils/run_cset_recipe.py
src/CSET/operators/__init__.py
tests/test_cli.py

Ensures the logs are output while the task is running and are recorded to a file.

Simplify logging

---

src/CSET/operators/plot.py

Also removes obslete references to the type of histogram (step filled, etc.) as this is no longer specified in the GUI and does not pass through into the recipes.

Add fixes for vertical line xlim and PDF xlim

---

src/CSET/operators/read.py

Removing a callback that fixed LFRic time data to be on hour to compare with UM, but testing was done on UM'ified data, running this on slammed only data reveals this is no longer needed.

Remove unneeded callback

---

cset-workflow/app/build_conda/bin/install-local-cset.sh

We now check that the value of `CSET_LOCAL_CSET_PATH` points to a file or directory that exists before using it.
Fixes #1202

Error build_conda when local CSET path not set

---

cset-workflow/app/install_website_skeleton/bin/install-website.sh
cset-workflow/meta/rose-meta.conf
cset-workflow/meta/rose-meta.conf.jinja2

This prevents errors such as:
```
WEB_DIR="$HOME/public_html/CSET/300m_UM_vs_LFRic_test" but the install_website_skeleton task failed with:
ln: failed to create symbolic link '/home/users/example.person/public_html/CSET/300m_UM_vs_LFRic_test': No such file or directory
```
Due to the intermediate CSET directory not already existing. These intermediate directories will now be created as needed.

Create needed parent directories when writing the website

---

docs/source/contributing/documentation.rst
docs/source/contributing/testing.rst
docs/source/usage/add-diagnostic.rst
pyproject.toml
requirements/environment.yml

We have stopped using tox for our development, as it doesn't offer enough over just using the cset-dev conda environment and the tools directly. It is also very slow on the networked filesystems our development environment uses. In addition we are pinned to an old, unmaintained version of tox to retain support for conda environments.
Given all of that this PR removes all references to tox from the documentation, removes the tox configuration, and removes the tox package from the cset-dev environment.
I've intentionally left it in the environment lock files, as actively removing it has a high chance of messy merge conflicts. It will get removed on the next weekly lockfile update after this PR is merged.
Aim to have all relevant checks ticked off before merging. See the [developer's …

Remove tox

---

src/CSET/operators/plot.py

I have changed the vertical line series y limit maximum from 10 hPa to 100 hPa and checked that the plots are correct by running the cset-workflow. This change is associated with #1210.

Updated vertical line series pressure maximum y limit to 100hPa.

---

src/CSET/operators/aggregate.py
src/CSET/operators/collapse.py
src/CSET/operators/misc.py
src/CSET/operators/plot.py
src/CSET/operators/read.py
src/CSET/recipes/generic_mlevel_domain_mean_vertical_profile_series_case_aggregation_hour_of_day.yaml
src/CSET/recipes/generic_mlevel_domain_mean_vertical_profile_series_case_aggregation_lead_time.yaml
src/CSET/recipes/generic_mlevel_domain_mean_vertical_profile_series_case_aggregation_validity_time.yaml
src/CSET/recipes/generic_mlevel_spatial_plot_sequence_case_aggregation_mean_hour_of_day.yaml
src/CSET/recipes/generic_mlevel_spatial_plot_sequence_case_aggregation_mean_lead_time.yaml
src/CSET/recipes/generic_mlevel_spatial_plot_sequence_case_aggregation_mean_validity_time.yaml
src/CSET/recipes/generic_plevel_domain_mean_vertical_profile_series_case_aggregation_hour_of_day.yaml
src/CSET/recipes/generic_plevel_domain_mean_vertical_profile_series_case_aggregation_lead_time.yaml
src/CSET/recipes/generic_plevel_domain_mean_vertical_profile_series_case_aggregation_validity_time.yaml
src/CSET/recipes/generic_plevel_spatial_plot_sequence_case_aggregation_mean_hour_of_day.yaml
src/CSET/recipes/generic_plevel_spatial_plot_sequence_case_aggregation_mean_lead_time.yaml
src/CSET/recipes/generic_plevel_spatial_plot_sequence_case_aggregation_mean_validity_time.yaml
src/CSET/recipes/generic_surface_domain_mean_time_series_case_aggregation_hour_of_day.yaml
src/CSET/recipes/generic_surface_domain_mean_time_series_case_aggregation_lead_time.yaml
src/CSET/recipes/generic_surface_domain_mean_time_series_case_aggregation_validity_time.yaml
src/CSET/recipes/generic_surface_spatial_plot_sequence_case_aggregation_mean_hour_of_day.yaml
src/CSET/recipes/generic_surface_spatial_plot_sequence_case_aggregation_mean_lead_time.yaml
src/CSET/recipes/generic_surface_spatial_plot_sequence_case_aggregation_mean_validity_time.yaml
src/CSET/recipes/surface_spatial_difference_case_aggregation_mean_hour_of_day.yaml
src/CSET/recipes/surface_spatial_difference_case_aggregation_mean_lead_time.yaml
src/CSET/recipes/surface_spatial_difference_case_aggregation_mean_validity_time.yaml
tests/conftest.py
tests/operators/test_aggregate.py
tests/operators/test_collapse.py
tests/operators/test_misc.py

Modify `ensure_aggregatable_across_cases` to ensure NetCDF cubes are correctly merged

---

src/CSET/operators/misc.py
tests/operators/test_misc.py

Checking for STASH codes only works when the base model is the UM.

Check for staggered grid with name rather than STASH in difference operator

---

src/CSET/_common.py
src/CSET/_workflow_utils/finish_website.py
tests/test_common.py

This uses a newly added human sort function, which ensures that strings containing numbers are sorted by value, rather than just character by character. This ensures that 9 sorts before 10, for example.
Fixes #1230

Fully sort website index

---

cset-workflow/flow.cylc

This should help with tasks occasionally timing out. Three hours is the practical limit for most compute systems without going into special long job queues.

Increase aggregation wallclock to 3 hours

---

cset-workflow/flow.cylc

This uses a new feature of cylc 8.4, and skips the job entirely.
The key consideration with this PR is portability, as not all sites might have cylc 8.4 yet.

Skip running dummy tasks

---

cset-workflow/app/fetch_fcst/bin/fetch-data-mass.py

It was failing when trying to decode the output stream, as we were not capturing the stream so there was nothing to decode.
As we don't need to capture it we can just remove the decoding attempt and all will be well.

Avoid accessing non-captured output in MASS fetch script

---

src/CSET/operators/plot.py

collapse output plot to vertical line (e.g. for global model)
Fixes #1252. 
Wraps min and max longitudes for instances where plotting > 1/2 globe (e.g. global model or CTC), enabling ongoing use of set_extents logic. Have also defined x1, x2, y1, y2 rather than compute bounds within set_extents calls.
Example output plots with global, cyclic tropical channel and LAM outputs: https://wwwspice/~huw.lewis/CSET/CSET_KScaleFirst/

Correct for instances where longitude plot bounds caused set_extent to

---

src/CSET/operators/plot.py

Fixes #1280 
Switches default colorbar location to horizontal below map plots.
See issue for example of sample LAM output (have not demonstrated use with global given dependencies on #1252 

1-line change to move default position of map colorbars to horizontal

---

pyproject.toml

The word "runN" appears in cylc filepaths, so it is a false positive.

Ignore codespell error for "runN"

---

src/CSET/operators/_colorbar_definition.json
src/CSET/operators/plot.py
src/CSET/operators/read.py

convert precipitation units to mm hr--1 and colourbar scale changed accordingly for surface_microphysical_rainfall_rate. Still requires change to colourbar

include precipitation specific colorbar and unit conversion

---

src/CSET/_workflow_utils/run_cset_recipe.py
tests/workflow_utils/test_run_cset_recipe.py

This removes the large (double) traceback when CSET crashes. These
tracebacks don't contain anything useful as the subprocess already logs
its own crash output.

Nicer output on crash from run_cset_recipe

---

cset-workflow/flow.cylc
cset-workflow/meta/rose-meta.conf
cset-workflow/meta/rose-meta.conf.jinja2
src/CSET/__init__.py
src/CSET/_workflow_utils/run_cset_recipe.py
src/CSET/operators/__init__.py
src/CSET/operators/write.py
tests/operators/test_write.py
tests/test_execute_recipe.py

This can be used to avoid writing the output for large runs, where the processed data might take up many terabytes and significantly slow processing.
I also sneaked in a minor improvement to the command logging in run_cset_recipe, so you can just take the logged command and run it directly, without having to worry about quoting things.
Fixes #1271

Add option to skip writing output

---

src/CSET/operators/_colorbar_definition.json

Updated toa radiation variables to use greyscale in default colorbar file

Updated default colorbar definition for radiation

---

src/CSET/operators/read.py
tests/operators/test_read.py

This prevents the callbacks from being applied multiple times to the same data, corrupting it. Additionally tests were added for these callbacks, which were previously untested.

Conditionally fix times in callbacks to avoid corrupting dates by double fixing

---

tests/operators/test_write.py

The call to get_metadata would prompt for the creation of a meta.json file, but this test was running outside of a temporary directory, so the meta.json was left in your current working directory after the test had run. The test now runs in a temporary directory, avoiding this issue.

Avoid writing meta.json outside tempdir during test

---

cset-workflow/flow.cylc

Retry failed tasks to improve workflow reliability against transient failures.
We can also reduce the wallclock, as it was higher than needed to reduce the chance of a failure, but if we are going to retry anyway we can get through quicker anyway.
Fixes #1312

Retry failed processing tasks

---

cset-workflow/app/preprocess_data/bin/preprocess.py
cset-workflow/app/preprocess_data/rose-app.conf
cset-workflow/flow.cylc
src/CSET/_workflow_utils/preprocess.py
tests/workflow_utils/test_preprocess.py

By putting the whole forecast into one file we only have to fix the metadata once, and it is much faster to load.
This takes most PROCESS tasks from 1 minute 30 seconds down to about 15 seconds.

Add preprocessing task to speed up workflow

---

src/CSET/_workflow_utils/run_cset_recipe.py

Fixes #1338. The internal logic for reading cset-workflow environment variable SKIP_WRITE was not operating as expected. This change to run_cset_recipe.py ensures that setting environment variable to T/F has the desired impact on cset bake commands.

Update logic for reading SKIP_WRITE environment variable when running cset-workflow

---

src/CSET/operators/_utils.py
src/CSET/operators/read.py
src/CSET/operators/transect.py
tests/operators/test_read.py
tests/operators/test_utils.py

Fixes #1337. Updated approach to add grid_latitude and grid_longitude as additional aux variables with read.py callback to ensure cube attributes are preserved when reading/writing intermediate files when processing latitude and longitude cubes (e.g. non-rotated grids). This preserves functionality of collapsing on [grid_latitude, grid_longitude] for all use cases. 

1337 fix implementation of grid latitude grid longitude callback for non rotated pole inputs

---

src/CSET/_workflow_utils/fetch_data.py
tests/workflow_utils/test_fetch_data.py

This is *much* faster than copying. As we rewrite the data in the pre-processing step this doesn't meaningfully change our external dependence on the data.

Symbolic link to raw filesystem data to avoid slow copy

---

src/CSET/operators/aggregate.py
src/CSET/operators/misc.py
tests/operators/test_misc.py

It will now equalise any time coordinate, rather than just one called "time". Notably this means it now supports the "hours" coordinate creating by aggregate_by_hour_of_day.
Fixes #1244

Support equalising hour coordinate in difference operator

---

src/CSET/operators/plot.py
tests/operators/test_plots.py

We were always using the coordinate from the first cube. This crashes when plotting multiple models on a single plot with different length coordinate, and can also plot incorrect values if they are the same length but have different offsets.

Pair cube with corresponding coordinate when plotting line series

---

src/CSET/operators/_utils.py
tests/operators/test_utils.py

This tests the error from get_cube_coordindex when a coordinate doesn't exist, and removes an unreachable except clause.

Improve testing of get_cube_coordindex

---

cset-workflow/includes/aoa_diag.cylc
cset-workflow/includes/basic_qq_plot.cylc
cset-workflow/includes/histogram_field.cylc
cset-workflow/includes/histogram_field_aggregation.cylc
cset-workflow/includes/histogram_field_aggregation_all.cylc
cset-workflow/includes/mlevel_transect.cylc
cset-workflow/includes/plevel_transect.cylc
cset-workflow/includes/profile_level.cylc
cset-workflow/includes/profile_level_aggregation.cylc
cset-workflow/includes/spatial_difference_field.cylc
cset-workflow/includes/spatial_difference_field_aggregation.cylc
cset-workflow/includes/spatial_field.cylc
cset-workflow/includes/spatial_field_aggregation.cylc
cset-workflow/includes/timeseries_field.cylc
cset-workflow/includes/timeseries_field_aggregation.cylc
cset-workflow/meta/rose-meta.conf
cset-workflow/meta/rose-meta.conf.jinja2

This prevents the workflow failing due to missing recipe variables.
Also includes a correction for the rose namespace for `SELECT_SUBAREA`. This was missed during review, and causes it to show up in its own section.

Add subarea variables to include files

---

src/CSET/recipes/generic_level_histogram_series_case_aggregation.yaml
src/CSET/recipes/generic_level_histogram_series_case_aggregation_hour_of_day.yaml
src/CSET/recipes/generic_level_histogram_series_case_aggregation_lead_time.yaml
src/CSET/recipes/generic_level_histogram_series_case_aggregation_validity_time.yaml
src/CSET/recipes/generic_surface_histogram_series_case_aggregation.yaml
src/CSET/recipes/generic_surface_histogram_series_case_aggregation_hour_of_day.yaml
src/CSET/recipes/generic_surface_histogram_series_case_aggregation_lead_time.yaml
src/CSET/recipes/generic_surface_histogram_series_case_aggregation_validity_time.yaml
src/CSET/recipes/generic_surface_single_point_time_series.yaml

Addresses #1402. Implements plotting of instantaneous outputs as default CSET behaviour across all plot types, where multiple input variables exist in input diagnostics. 

Add non-aggregated cell_methods contraint to all histogram plotting recipes for surface and level variables

---

.github/workflows/conda-lock.yml
.github/workflows/pre-commit-update.yml
.github/workflows/pull-request-checks.yml
.github/workflows/release.yml
.github/workflows/weekly-checks.yml

This will prevent us from wasting too many minutes when a job gets stuck, and hopefully alert us to the situation faster.
I've chosen 20 minutes as it is short enough to avoiding wasting too many minutes, compared to the default 6 hours, while it is long enough to avoiding having to change the limit for most jobs.
If a job does need longer than 20 minutes, the limit can be increased on a per-job basis.

Set 20 minute runtime limit for GitHub Actions jobs

---

tests/test_cli.py

This now actually checks each of the subparsers work.

More robustly test command line argument parser

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other.md

No one has ever really filled it in usefully, and it is covered in the reproducing section.
Also fixes some inconsistencies in the issue type descriptions.

Remove environment section from bug report issue template

---

src/CSET/operators/aggregate.py
src/CSET/operators/collapse.py
src/CSET/operators/read.py
tests/operators/test_collapse.py
tests/operators/test_read.py

Fixes #1447. Ensures data are rolled as well as hour points where sorting of inputs to hour 0-23 required when adding hour coordinate to cubes. Only plotting common time points also fixed by ensuring all time coordinates have common base time in callbak. 

Align time units and fix diurnal cycle aggregation bug

---

src/CSET/workflow/files/app/install_website_skeleton/file/html/placeholder.html
src/CSET/workflow/finish_website.py
tests/workflow/test_finish_website.py

The Met Office webserver specific issue that blocked the .conf extension has been fixed.
Fixes #1455

Rename rose-suite.conf.txt to rose-suite.conf

---

Makefile
docs/source/contributing/getting-started.rst
src/CSET/workflow/files/bin/app_env_wrapper

Having this link causes editable installs to pick up the linked conda environment inside the extract-workflow command. Now, instead of creating that link the workflow will automatically try to use an environment named "cset-dev" if there is no linked workflow.
A temporary cleanup command has been added to `make setup`, to fix this issue for those already affected. We can probably drop this line in a few weeks as those affected (developers in the past week) will have all updated.
Fixes #1459

Remove conda-environment link from development workflow to fix failing tests

---

tests/conftest.py
tests/operators/test_plots.py

This prevents them dumping their artefacts in the repository when the tests are run. Additionally a couple direct reads were moved to fixtures to support this.

Use temporary working directory for plotting tests

---

src/CSET/cset_workflow/flow.cylc

Attempt to fix running of CSET with ensemble data for more than ten variables, for which is currently crashes.
Fixes #1503

Allow ensembles to run for more than ten variables

---

.pre-commit-config.yaml

The "ruff" hook is deprecated; this avoids a warning while running pre-commit.

Update the pre-commit hook ID for ruff-check

---

docs/source/changelog.rst
src/CSET/cset_workflow/meta/diagnostics/rose-meta.conf

correct METHOD for time aggregation from STD to STD_DEV in rose-meta.conf in line with iris.analysis methods.

Correct description for standard deviation time aggregation method in rose edit

---

.github/workflows/pull-request-checks.yml

We should aim to increase this in future, but it is blocking pull requests currently. The main issue is that it will error when the coverage is too low, even if you new code isn't covered.

Reduce required code coverage

---

src/CSET/operators/collapse.py
src/CSET/operators/read.py
src/CSET/recipes/generic_level_domain_mean_time_series_case_aggregation_all.yaml
src/CSET/recipes/generic_level_domain_mean_time_series_case_aggregation_hour_of_day.yaml
src/CSET/recipes/generic_level_domain_mean_time_series_case_aggregation_lead_time.yaml
src/CSET/recipes/generic_level_domain_mean_time_series_case_aggregation_validity_time.yaml
src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_all.yaml
src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_hour_of_day.yaml
src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_lead_time.yaml
src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_validity_time.yaml
src/CSET/recipes/generic_surface_domain_mean_time_series_case_aggregation_all.yaml
src/CSET/recipes/generic_surface_domain_mean_time_series_case_aggregation_hour_of_day.yaml
src/CSET/recipes/generic_surface_domain_mean_time_series_case_aggregation_lead_time.yaml
src/CSET/recipes/generic_surface_domain_mean_time_series_case_aggregation_validity_time.yaml
tests/operators/test_collapse.py

Fixes #1532.
Adds the check for overlapping times if multi-model inputs to the generic collapse.py function. This enables removal of the temporary _remove_time0 function call from read.py (was in preprocess.py).
Note this requires updates to aggregation recipes to first call ensure_aggregatable_across_cases to organise input cubelists before being able to check on compatibility of input times.  

Update collapse to ensure processing overlapping times only where multiple model inputs

---

scripts/generate_rose_meta.py
scripts/sort_json.py
src/CSET/cset_workflow/app/assign_model_colours/bin/assign_model_colours.py
src/CSET/cset_workflow/app/fetch_fcst/bin/fetch-data-filesystem.py
src/CSET/cset_workflow/app/fetch_fcst/bin/fetch-data-http.py
src/CSET/cset_workflow/app/fetch_fcst/bin/fetch-data-mass.py
src/CSET/cset_workflow/app/finish_website/bin/finish_website.py
src/CSET/cset_workflow/app/housekeeping/bin/housekeep.sh
src/CSET/cset_workflow/app/install_website_skeleton/bin/install-website.sh
src/CSET/cset_workflow/app/run_cset_recipe/bin/run_cset_recipe.py
src/CSET/cset_workflow/app/send_email/bin/send_email.py
src/CSET/cset_workflow/install_restricted_files.sh
src/CSET/extract_workflow.py
tests/test_graph.py
tests/workflow_utils/test_install_workflow.py

Mostly done for visual consistency, but this does have a couple positive technical effects:
1. Using /usr/bin/env should be more portable to systems like MacOS with no or ancient versions of bash.
2. Using `#!/usr/bin/env` for script detection should avoid marking the flow.cylc as executable.

Normalise shebangs to use `/usr/bin/env`

---

tests/conftest.py

Largely to satisfy my type checker, but it also helps editor suggestions.

Add return type for `tmp_working_dir` fixture

---

src/CSET/_common.py
tests/test_common.py

A useful helper function for allowing multiline strings to be indented with the test of the code.
This function is not used yet, but I wanted to get it ahead of using it in a coming change, to make review easier.

Add sstrip utility function

---

src/CSET/recipes/__init__.py
tests/test_recipes.py

A warning is too scary for a harmless occurrence, and we unpack existing recipes a lot inside the workflow.

Log rather than warn for existing unpacked recipes

---

src/CSET/__init__.py
src/CSET/_common.py
src/CSET/operators/__init__.py
tests/test_cli.py
tests/test_common.py
tests/test_execute_recipe.py

This allows easier testing and allows using the recipe parser when not executing a recipe, such as when parbaking.
Additionally the handling of the `--input-dir` argument is moved inside parse_variable_options so all the parsing code is in one place.

Parse recipe separately from executing it

---

src/CSET/cset_workflow/app/assign_model_colours/bin/assign_model_colours.py
src/CSET/cset_workflow/flow.cylc
src/CSET/cset_workflow/lib/python/jinja_utils.py
tests/workflow_utils/test_jinja_utils.py

This allows transporting structured data from cylc into a task, without worrying about that information being mangled by the multiple layers of shell in between.
It is then used for safely transporting model names.
The jinja_utils functions that are not tested will be removed in #1332.

Add `b64json` jinja utility function

---

src/CSET/operators/constraints.py
tests/operators/test_constraints.py
tests/operators/test_filters.py

Adding in a constraint to remove a single ensemble member to allow ensemble statistics to be calculated with and without the control member (for example).
Fixes #1628

Add constraint to remove single ensemble member

---

src/CSET/operators/plot.py
tests/operators/test_plot.py

This allows us to remove the complicated task family hierarchy in #1332.
We also skip if we can't get the information from cylc such as when not in a workflow.

Don't set plot date if DO_CASE_AGGREGATION

---

src/CSET/cset_workflow/app/bake_recipes/bin/bake.sh
src/CSET/cset_workflow/app/bake_recipes/bin/baker.sh
src/CSET/cset_workflow/app/bake_recipes/rose-app.conf
src/CSET/cset_workflow/flow.cylc

This uses rose-bunch to bake multiple recipes in parallel inside of a single cylc job. This makes it significantly faster than running thousands of tiny jobs.
To allow it to dynamically find the available jobs, cylc executes the baker.sh script, which writes a rose optional configuration specifying the recipes and parallelism, then runs the rose app using that configuration.

#837 part 1: Add `bake_recipes` rose app

---

src/CSET/cset_workflow/app/parbake_recipes/bin/parbake.py
src/CSET/cset_workflow/app/parbake_recipes/rose-app.conf
src/CSET/cset_workflow/flow.cylc
tests/workflow_utils/test_parbake_recipes.py

#837 part 3: Add `parbake_recipes` rose app

---

src/CSET/cset_workflow/app/bake_recipes/bin/baker.sh

This avoids task failures if we have no aggregation tasks enabled. I've also switched to using find over globbing as it avoids a potentual bug if the directory exists, but doesn't contain any recipes, where we would try and bake a literal "*.yaml" file.

Skip baking if we have no recipes

---

src/CSET/cset_workflow/app/bake_recipes/bin/baker.sh
src/CSET/cset_workflow/app/bake_recipes/rose-app.conf

Rose bunch incremental mode means that tasks that have suceeded are not rerun, so that only failed tasks need to be. This is the default, but it has been made explicit to be sure it is
enabled.
There are two issues fixed in this commit. The first is that we were
using the CYLC_TASK_TRY_NUMBER variable to determine if we were
retrying, which gets reset on a manual cylc trigger.
CYLC_TASK_SUBMIT_NUMBER is not, so that all runs after the first will
now run serially, regardless of how they were triggered.
The other issue was that rose_bunch was never running tasks
incrementally due to us changing the parallelism in the configuration.
We now avoid this by updating the recorded configuration in rose_bunch's
database to match.
This is decidedly a hack, but seems to work well, and means that we …

Use rose-bunch incremental mode when baking

---

src/CSET/cset_workflow/flow.cylc

They are not portable to non-SLURM systems. Also removed the platform from the DUMMY_TASK family, so all tasks use the same platform for simplicity. This shouldn't slow things down as it runs in skip mode anyway.
Fixes #1755

Remove resource directives from flow.cylc
