MetOffice/CSET

- pyproject.toml
- requirements/environment.yml
- src/CSET/operators/RECIPES/__init__.py
- src/CSET/operators/average.py
- src/CSET/tasks/demo_pointstat/verpy/plot_met_stats.py
This PR is based on #56 and will need rebasing when that is merged.
https://conda-forge.org/blog/posts/2021-06-16-graykull-step-by-step/
https://conda-forge.org/docs/maintainer/adding_pkgs.html
https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
> Improvements around packaging

- .github/workflows/pr_ci.yml
- requirements/environment.yml
This prevents PRs being filled up with these comments, drowning out other conversation.
> Make PR coverage reports edit last comment

- docs/source/usage/index.rst
- docs/source/working-practices/index.rst
Will want further working to link between instruction under usage and instructions under working practices.
> Improve installation instructions

- requirements/environment.yml
> Relax version requirement for sphinx

- pyproject.toml
Bump version number after 0.2.0 release.
> Increase version number

- README.md
- pyproject.toml
The current description wasn't really general enough to cover what CSET does; it has been updated.
> Update description of CSET

- README.md
> Update working practices link to point to contributing docs

- pyproject.toml
As we have just released v0.3.0, this will be our next release.
> Update version to 0.4.0

- src/CSET/operators/plot.py
- src/CSET/operators/write.py
> Make plot.contour_plot and write.write_cube_to_nc return a cube

- .github/workflows/conda-lock.yml
> Use static branch name while updating lock files

- pyproject.toml
Now we have released v0.4, 0.5 will be our next.
> Bump version to 0.5.0

- docs/source/reference/operators.rst
- src/CSET/operators/collapse.py
- src/CSET/operators/plot.py
Partial work on improving the contour plot per #240. It is not yet complete, but is already a lot better than `qplt.contourf`, so we want it for the away day on Monday.
> Improve contour plot

- src/CSET/operators/convection.py
> Minor bug fix to cape ratio documentation

- src/CSET/__init__.py
- src/CSET/operators/__init__.py
- src/CSET/operators/plot.py
Fixes #253
Fixes #114
Fixes #306
> Provide unified download of output

- src/CSET/operators/filters.py
- tests/operators/test_filters.py
Filter operator that takes multiple constraints and returns a single cube for each.
Fixes #357
> Add filter_multiple_cubes operator

- tests/test_run_recipes.py
Improves test coverage a little.
> Test exception for invalid output directory

- tests/operators/test_filters.py
This was a test case that was missed in the original PR.
> Test no constraints given to filter_multiple_cubes

- pyproject.toml
- src/CSET/operators/plot.py
- tests/operators/test_plots.py
> Unify postage stamp plots

- tests/operators/test_write.py
Fixes the broken check on main.
> Remove excess whitespace to satisfy pre-commit formatter

- docs/source/contributing/getting-started.rst
I can never intuitively find the developer install guide so renaming this in hope it is clearer
> Retitle code and tooling setup page

- src/CSET/operators/regrid.py
- tests/operators/test_regrid.py
Add some additional tests to the regrid operator, and fix a couple minor bugs that showed up during testing.
This PR targets a branch, so merge directly if happy with it.
> Additional regridding tests

- src/CSET/_common.py
- src/CSET/operators/filters.py
- src/CSET/operators/misc.py
- src/CSET/operators/read.py
- src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
- src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
- tests/operators/test_read.py
- tests/test_common.py
> Non-UMified LFRic handling

- cset-workflow/app/install_website_skeleton/file/html/index.html
Fixes https://github.com/MetOffice/CSET/issues/432
> Add feedback links to CSET front page

- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/index.rst
Add a changelog file backdated with the previous couple releases worth of changes.
Fixes #467
Aim to have all relevant checks ticked off before merging. See the [contribution guide](https://metoffice.github.io/CSET/contributing/) for more detail.
> Add changelog file

- .github/ISSUE_TEMPLATE/bug_report.md
Fix spelling in GitHub issue template.
> Fix spelling in github issue template

- src/CSET/operators/plot.py
Fixes ruff lint error for post python 3.9. See https://docs.astral.sh/ruff/rules/zip-without-explicit-strict/
> Fix new ruff lint

- .github/workflows/documentation.yml
- .github/workflows/pull_request_checks.yml
- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/contributing/getting-started.rst
- docs/source/contributing/git.rst
> Add sphinx linkcheck

- docs/source/changelog.rst
- src/CSET/__init__.py
- tests/test_cli.py
- tests/test_data/addopts_test_recipe.yaml
> Test and fix `CSET_ADDOPTS` with lists

- docs/source/usage/workflow-installation.rst
clarification to use cylc gui in interactive mode as it otherwise becomes unreactive.
Fixes #
> Update cylc gui instructions in workflow-installation.rst

- docs/source/conf.py
Very small change to update the copy right year in the footer of the documentation.
> Update documentation copyright year

- .github/pull_request_template.md
This means that single commit PRs populate the template properly.
> Remove unneeded title from PR template

- docs/source/changelog.rst
- docs/source/contributing/getting-started.rst
- docs/source/contributing/git.rst
- docs/source/usage/add-diagnostic.rst
- src/CSET/operators/__init__.py
Remove suggestion to create branch on GitHub, as it makes it difficult to push code from your local computer initially. Then generally update and improve that documentation.
Fixes #559
> Improve "Add a new diagnostic" documentation

- pyproject.toml
Just makes it show up in the package indexes a bit nicer.
> Add some more classifiers to the package metadata

- docs/source/changelog.rst
> Fix a changelog descrepancy that arose during conflict resolution

- docs/source/changelog.rst
- src/CSET/operators/read.py
- src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
- src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
- tests/operators/test_read.py
Also includes a general refactoring of the read_cubes operator.
Fixes #532
> Normalise LFRic cubes during load

- docs/source/usage/add-diagnostic.rst
Tiny change to the section that details linking yaml recipes into the workflow and spelling it out more.
> Clarify linking the recipe into the rest of CSET

- .github/pull_request_template.md
Minor wording tweak to GenAI checklist item.
> Tweak GenAI attribution PR check wording

- docs/source/changelog.rst
Follow up to #353, just adding a changelog entry.
> Add changelog entry

- .github/workflows/documentation.yml
- .github/workflows/pull_request_checks.yml
- docs/source/changelog.rst
> Include cartopy downloaded resources in GitHub Actions cache

- .github/workflows/pull_request_checks.yml
- docs/source/changelog.rst
Separated out from #356, as its a nice independent change.
> Group installation logs in testing workflow

- src/CSET/operators/__init__.py
> Log whether operator first arg comes from previous step or recipe

- docs/source/changelog.rst
- src/CSET/recipes/inflow_layer_properties_plot.yaml
> 661 inflow properties recipe fix

- src/CSET/_common.py
Nothing that can reach here is lacking a read method, so this code can never run.
> Remove unreachable code

- docs/source/changelog.rst
Lets us make the v24.6.0 release.
> Add v24.6.0 release notes

- docs/source/changelog.rst
Fixes the formatting of the changelog, that was slightly broken in a couple entries.
> Fix changelog formatting

- cset-workflow/flow.cylc
- docs/source/changelog.rst
> Fixed metplus config issue 

- docs/source/contributing/testing.rst
Fixes #696, where the second code block does not render.
> Correct rst syntax added in #696

- docs/source/contributing/index.rst
Adapted from the ESMValTool documentation at
https://docs.esmvaltool.org/en/latest/community/code_documentation.html#pull-request-title
> Improve PR title documentation in developer's guide

- docs/source/contributing/index.rst
> Minor wording tweak in marking PR as ready to review docs

- docs/source/conf.py
Isn't an issue yet, but will fix issues if we have multiple versions of documentation in future.
> Add canonical URL links to documentation

- docs/source/contributing/testing.rst
Also fix the heading, as previously it was a \<h1\> rather than a \<h2\>.
> Clarify running specific tests

- cset-workflow/includes/lfric_deterministic_domain_mean_surface_time_series.cylc
- cset-workflow/includes/lfric_plot_spatial_surface_model_field.cylc
- src/CSET/operators/constraints.py
- src/CSET/recipes/generic_plevel_spatial_plot_sequence.yaml
- src/CSET/recipes/lfric_generic_domain_mean_vertical_profile_series.yaml
- src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
- src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
> Fix SET_SUBAREA being required to run some LFRIC recipes

- tests/operators/test_plots.py
> Test vertical plotting with a filename specified

- tests/test_run_recipes.py
> Test running recipes with no collate steps and running with a specified style file

- cset-workflow/meta/rose-meta.conf
> Remove unneeded rose edit setting

- docs/source/reference/internal.rst
It would be more convenient to view the documentation for these internal functions on the website.
> Add _utils operators to internal function documentation

- docs/source/reference/cli.rst
- docs/source/reference/recipe-format.rst
> Tidy up documentation around recipes and cset bake command, introducing examples

- tests/operators/test_regrid.py
> Filter irrelevant warning raised by regrid test

- src/CSET/operators/read.py
- tests/operators/test_read.py
This ensures the coordinate shows up properly, and allows it to merge.
GitHub Copilot was used in this pull request.
> Convert time AuxCoord to DimCoord for LFRic data

- docs/source/changelog.rst
Adds release notes. Going to merge without review as it just touches documentation in a non-functional way, and also we are a little time pressed.
> Add release notes for CSET v24.8.0

- .github/dependabot.yml
- .github/workflows/conda-lock.yml
- .github/workflows/documentation.yml
- .github/workflows/pre-commit-update.yml
- .github/workflows/pull_request_checks.yml
- .github/workflows/release.yml
- .github/workflows/weekly-checks.yml
GitHub lost some of my trust after the upload artifact v4.4.0 debacle. Therefore we will now pin to specific versions, and let Dependabot make PRs to update us.
Fixes #833
> Pin GitHub Actions to specific commits to prevent random breakage

- docs/source/getting-started/installation.rst
> Note that all documentation shell examples use bash

- src/CSET/_workflow_utils/fetch_data.py
> Fix typo in comment

- src/CSET/_workflow_utils/fetch_data.py
> Remove HTTP status check as urlopen already does it

- src/CSET/_common.py
- tests/test_common.py
> Test templating variables into recipe parser

- tests/test_recipes.py
> Test recipe listing and detailing functions

- src/CSET/operators/regrid.py
> Fix type signature

- docs/source/index.rst
> Change CSET introduction on documentation welcome page

- cset-workflow/meta/rose-meta.conf
Fixes #665
Updates the documentation in the GUI for WEB_ADDR on main page for clarity.
> Update to WEB_ADDR documentation.

- .github/workflows/conda-lock.yml
> Target lockfile update PR to source branch

- src/CSET/recipes/generic_surface_histogram_series.yaml
> Fix no title in surface histogram plots

- src/CSET/_common.py
- src/CSET/_workflow_utils/finish_website.py
- src/CSET/operators/__init__.py
- src/CSET/operators/plot.py
It isn't in any performance hot paths, and makes inspecting it much nicer.
> Format JSON when writing

- src/CSET/operators/plot.py
Not all spatial plots are contour plots nowdays.
> Generalise spatial plot log message

- src/CSET/operators/read.py
- tests/operators/test_read.py
> Seperate words in callback function name with _ so it is easier to read

- cset-workflow/meta/rose-meta.conf
> Fix typo in rose-edit help

- .github/ISSUE_TEMPLATE/config.yml
This allows us to disable the blank issue option, and link to the discussion forum for questions.
> Add configuration file for GitHub Issue templates

- src/CSET/operators/_utils.py
- tests/operators/test_utils.py
Non-matching attributes and coordinates that are not present on all cubes are removed.
> Add utility function for equalising attributes

- src/CSET/operators/_colorbar_definition.json
> unify colourbar for cloud_base_altitude between um and lfric

- src/CSET/operators/collapse.py
- tests/operators/test_collapse.py
Adds collapse by validity time operator.
Fixes #1030
> Collapse by validity time

- src/CSET/operators/__init__.py
> Accept microsecond precision in iris times

- cset-workflow/rose-suite.conf.example
Rose edit will not open as a variable is not set.
> Fix issue with rose-suite.conf variable

- src/CSET/operators/read.py
> Deduplicate an unlimited amount of STASH warnings

- cset-workflow/app/fetch_fcst/bin/fetch-data-mass.py
This was missed when this code was ported from an old branch, as it predated this requirement.
Not tested as MASS is currently down.
> Implement required return value for MASSFileRetriever

- cset-workflow/app/install_website_skeleton/file/html/static/style.css
This prevents it overflowing the boxes, and makes it nicer to read.
> Break long names in sidebar

- src/CSET/operators/_colorbar_definition.json
- tests/operators/test_plots.py
> Fix JSON colorbar entries and ensure we use LFRic names

- .pre-commit-config.yaml
- cset-workflow/bin/app_env_wrapper
This will ensure all shell scripts have some basic checks.
> Add shellcheck to pre-commit hooks

- src/CSET/operators/_colorbar_definition.json
> Fix color bars

- src/CSET/operators/_colorbar_definition.json
> Fix colorbar for geopotential height differences

- tests/test_cli.py
> Test matplotlib font logs are filtered out

- src/CSET/operators/plot.py
> Extract cube from CubeList for histogram plot

- docs/source/getting-started/run-recipe.rst
- docs/source/getting-started/visualise-recipe.rst
Fixes #1209
We can't easily underline it due to the theme we are using, but hopefully this makes it clearer that they are hyperlinks.
> Draw attention to the hyperlink to download the example

- src/CSET/_workflow_utils/finish_website.py
> Sort diagnostics by display name

- cset-workflow/flow.cylc
- cset-workflow/includes/deterministic_domain_histogram_series_case_study_aggregation.cylc
- cset-workflow/includes/deterministic_domain_histogram_series_case_study_aggregation_lead_time.cylc
- cset-workflow/includes/deterministic_domain_mean_surface_time_series_case_study_aggregation_hour_of_day.cylc
- cset-workflow/includes/deterministic_domain_mean_surface_time_series_case_study_aggregation_lead_time.cylc
- cset-workflow/includes/deterministic_domain_mean_surface_time_series_case_study_aggregation_validity_time.cylc
- cset-workflow/includes/deterministic_domain_mean_vertical_model_level_profile_series_case_study_aggregation_hour_of_day.cylc
- cset-workflow/includes/deterministic_domain_mean_vertical_model_level_profile_series_case_study_aggregation_lead_time.cylc
- cset-workflow/includes/deterministic_domain_mean_vertical_model_level_profile_series_case_study_aggregation_validity_time.cylc
- cset-workflow/includes/deterministic_domain_mean_vertical_pressure_profile_series_case_study_aggregation_hour_of_day.cylc
- cset-workflow/includes/deterministic_domain_mean_vertical_pressure_profile_series_case_study_aggregation_lead_time.cylc
- cset-workflow/includes/deterministic_domain_mean_vertical_pressure_profile_series_case_study_aggregation_validity_time.cylc
- cset-workflow/includes/deterministic_domain_surface_histogram_series_case_study_aggregation.cylc
- cset-workflow/includes/deterministic_domain_surface_histogram_series_case_study_aggregation_lead_time.cylc
- cset-workflow/includes/plot_spatial_mlevel_model_field_case_study_aggregation_hour_of_day.cylc
- cset-workflow/includes/plot_spatial_mlevel_model_field_case_study_aggregation_lead_time.cylc
- cset-workflow/includes/plot_spatial_mlevel_model_field_case_study_aggregation_validity_time.cylc
- cset-workflow/includes/plot_spatial_plevel_model_field_case_study_aggregation_hour_of_day.cylc
- cset-workflow/includes/plot_spatial_plevel_model_field_case_study_aggregation_lead_time.cylc
- cset-workflow/includes/plot_spatial_plevel_model_field_case_study_aggregation_validity_time.cylc
- cset-workflow/includes/plot_spatial_surface_model_field_case_study_aggregation_hour_of_day.cylc
- cset-workflow/includes/plot_spatial_surface_model_field_case_study_aggregation_lead_time.cylc
- cset-workflow/includes/plot_spatial_surface_model_field_case_study_aggregation_validity_time.cylc
- cset-workflow/includes/spatial_surface_difference_case_study_aggregation_hour_of_day.cylc
- cset-workflow/includes/spatial_surface_difference_case_study_aggregation_lead_time.cylc
- cset-workflow/includes/spatial_surface_difference_case_study_aggregation_validity_time.cylc
Alters the memory and wall clock time for the aggregation cases to handle multiple cases.
Fixes #1235 
> Increase memory and wall clock limits for case aggregation tasks

- docs/source/changelog.rst
> Add changelog entry for v25.3.0

- cset-workflow/app/housekeeping/bin/housekeep.sh
It removed an intermediate folder that we no longer create.
> Remove unneeded deletion from housekeeping

- docs/source/usage/add-site.rst
- docs/source/usage/index.rst
Rendered documentation: https://tmpweb.net/pvP40inDb7lk/usage/add-site
> Document adding a site-specific configuration

- docs/source/changelog.rst
> Add release notes for v25.3.1

- cset-workflow/app/fetch_fcst/bin/fetch-data-mass.py
This allows better recovery after a failed job.
> Overwrite partially downloaded files from MASS

- cset-workflow/requirements/workflow-locks/py310-lock-linux-64.txt
- cset-workflow/requirements/workflow-locks/py311-lock-linux-64.txt
- cset-workflow/requirements/workflow-locks/py312-lock-linux-64.txt
- cset-workflow/requirements/workflow-locks/py313-lock-linux-64.txt
> Update workflow CSET package

- src/CSET/operators/read.py
- tests/operators/test_read.py
> Refactor lfric_time_callback

- src/CSET/_workflow_utils/run_cset_recipe.py
- src/CSET/operators/__init__.py
- tests/test_execute_recipe.py
- tests/workflow_utils/test_run_cset_recipe.py
A cleanup change before larger refactoring to how CSET bake is run.
> Move diagnostic archive creation into bake

- src/CSET/_workflow_utils/run_cset_recipe.py
A small visual fix for something I missed (broke) in #1329.
> Correctly format print-based logging in run_cset_recipe.py

- src/CSET/recipes/transect.yaml
> Add category to transect recipe

- src/CSET/operators/_stash_to_lfric.py
> Add additional STASH to LFRic mappings

- cset-workflow/app/assign_model_colours/bin/assign_model_colours.py
- cset-workflow/app/assign_model_colours/rose-app.conf
- cset-workflow/flow.cylc
- cset-workflow/includes/histogram_plevel_field.cylc
- cset-workflow/includes/histogram_plevel_field_aggregation.cylc
- cset-workflow/includes/histogram_plevel_field_aggregation_all.cylc
- cset-workflow/includes/histogram_surface_field.cylc
- cset-workflow/includes/histogram_surface_field_aggregation.cylc
- cset-workflow/includes/histogram_surface_field_aggregation_all.cylc
- cset-workflow/lib/python/jinja_utils.py
- src/CSET/_workflow_utils/run_cset_recipe.py
- src/CSET/operators/plot.py
- src/CSET/operators/read.py
- src/CSET/recipes/generic_plevel_histogram_series.yaml
- src/CSET/recipes/generic_plevel_histogram_series_case_aggregation.yaml
- src/CSET/recipes/generic_plevel_histogram_series_case_aggregation_lead_time.yaml
- src/CSET/recipes/generic_surface_histogram_series.yaml
- src/CSET/recipes/generic_surface_histogram_series_case_aggregation.yaml
- src/CSET/recipes/generic_surface_histogram_series_case_aggregation_lead_time.yaml
- tests/operators/test_read.py
Handles #1307, partly..(*) (histogram plots, per case and aggregated, can now be plotted with "all models on one plot" approach; cset-workflow users have to set MULTIMODEL rose-suite.conf variable to True)
(*) in fact, the issue deals only with histogram plots but the broader idea was to use this approach for other line plots, which is work in progress.
> Plot all models on a single histogram plot

- docs/source/changelog.rst
- docs/source/contributing/releases.rst
> Add v25.5.0 release notes and document more of the release process

- cset-workflow/meta/diagnostics/rose-meta.conf
> Correct model level sort key in rose edit

- requirements/environment.yml
Issue described in https://github.com/SciTools/iris/issues/6417
> Bump minimum iris version to avoid dask issues

- docs/source/reference/cli.rst
> Fix formatting of cset bake example documentation

- cset-workflow/includes/profile_level.cylc
- cset-workflow/includes/profile_level_aggregation.cylc
- src/CSET/operators/plot.py
- src/CSET/recipes/generic_level_domain_mean_vertical_profile_series.yaml
- src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_hour_of_day.yaml
- src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_lead_time.yaml
- src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_validity_time.yaml
> Multiple model lines on vertical profiles

- docs/source/changelog.rst
> Add CSET v25.5.1 release notes to changelog

- .github/workflows/conda-lock.yml
- .github/workflows/pre-commit-update.yml
- .github/workflows/pull-request-checks.yml
- .github/workflows/release.yml
- .github/workflows/weekly-checks.yml
- docs/source/contributing/getting-started.rst
- docs/source/contributing/testing.rst
A little bit of cleanup after our release.
> Various minor GitHub Actions improvements

- docs/source/changelog.rst
> Add CSET v25.5.2 release notes to changelog

- cset-workflow/app/install_website_skeleton/file/html/placeholder.html
- src/CSET/_workflow_utils/finish_website.py
- tests/workflow_utils/test_finish_website.py
Copies the rose-suite.conf file associated with cset-workflow run to the web directory, and provides link from website.
> Add copy of local rose-suite.conf into output pages

- src/CSET/__init__.py
- tests/test_cli.py
> Simplify and test conversion from --input-dir to --INPUT_PATHS

- src/CSET/operators/read.py
- tests/operators/test_read.py
Suggestions for PR #1433. They are a little expansive to do as a comment, so I've made another PR instead, based on the appropriate branch. Just merge the PR to accept the changes.
> Suggestions for PR #1433

- MANIFEST.in
Otherwise everything that is tracked by git is included in our packages.
> Exclude additional VCS files from sdist manifest to prevent them being included in published packages

- src/CSET/workflow/files/flow.cylc
- src/CSET/workflow/files/meta/diagnostics/rose-meta.conf
- src/CSET/workflow/preprocess.py
- tests/workflow/test_preprocess.py
Reduce size of intermediate preprocess file and amount of callback functions applied to unused variables.
> Filter down to required variables during workflow preprocessing to minimise data size

- docs/source/contributing/getting-started.rst
As it is simpler to use we want it first in the documentation.
> Move `make setup` documentation to make it more prominent

- src/CSET/operators/plot.py
- tests/operators/test_plots.py
> Include discrete colourbar for spatial visibility_in_air plots

- docs/source/usage/add-diagnostic.rst
Based on #1474, so should be merged afterwards.
> Clarify adding a recipe to the CSET workflow

- src/CSET/cset_workflow/flow.cylc
> Increases memory for ensemble plotting

- .gitattributes
- docs/source/usage/add-diagnostic.rst
- docs/source/usage/add-site.rst
These were only partially converted in the original move.
> Correct workflow path in documentation

- src/CSET/operators/plot.py
- src/CSET/recipes/surface_spatial_difference.yaml
- src/CSET/recipes/surface_spatial_difference_case_aggregation_mean_all.yaml
- src/CSET/recipes/surface_spatial_difference_case_aggregation_mean_hour_of_day.yaml
- src/CSET/recipes/surface_spatial_difference_case_aggregation_mean_lead_time.yaml
- src/CSET/recipes/surface_spatial_difference_case_aggregation_mean_validity_time.yaml
> Update surface_spatial_difference recipes to shorten plot title widths

- src/CSET/recipes/surface_spatial_difference_case_aggregation_mean_lead_time.yaml
> Uppercase "Difference" in plot title

- Makefile
The TLS certificate issues that were holding us back at the Met Office have now been resolved.
> Use python 3.13 when creating developer conda environment

- src/CSET/cset_workflow/app/finish_website/bin/finish_website.py
- src/CSET/cset_workflow/app/send_email/bin/send_email.py
They are a pain to test (the file has to be run in a subprocess), and there is no logic to go wrong, so the value of testing them is minimal.
> Exclude script entry points from coverage

- src/CSET/operators/constraints.py
- tests/operators/test_filters.py
> Update cell_methods constraint to handle maximum and minimum cell methods
